// flow-typed signature: c3ad0b0fd992f73b3b685e6549243fae
// flow-typed version: <<STUB>>/fuse_v^0.4.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fuse'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fuse' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fuse/bin/fuse' {
  declare module.exports: any;
}

declare module 'fuse/lib/fuse' {
  declare module.exports: any;
}

declare module 'fuse/lib/index' {
  declare module.exports: any;
}

declare module 'fuse/lib/mustache' {
  declare module.exports: any;
}

declare module 'fuse/test/javascript/expected/depends/basic-depends-result' {
  declare module.exports: any;
}

declare module 'fuse/test/javascript/expected/import/basic-import-result' {
  declare module.exports: any;
}

declare module 'fuse/test/javascript/expected/include/basic-include-result' {
  declare module.exports: any;
}

declare module 'fuse/test/javascript/expected/twoDepends/result' {
  declare module.exports: any;
}

declare module 'fuse/test/javascript/src/depends/basic-depends' {
  declare module.exports: any;
}

declare module 'fuse/test/javascript/src/depends/depends-one' {
  declare module.exports: any;
}

declare module 'fuse/test/javascript/src/import/basic-import' {
  declare module.exports: any;
}

declare module 'fuse/test/javascript/src/import/import-one' {
  declare module.exports: any;
}

declare module 'fuse/test/javascript/src/include/basic-include' {
  declare module.exports: any;
}

declare module 'fuse/test/javascript/src/include/include-one' {
  declare module.exports: any;
}

declare module 'fuse/test/javascript/src/lint/lint' {
  declare module.exports: any;
}

declare module 'fuse/test/javascript/src/lint/lintfree' {
  declare module.exports: any;
}

declare module 'fuse/test/javascript/src/noDepends/input' {
  declare module.exports: any;
}

declare module 'fuse/test/javascript/src/twoDepends/depends-one' {
  declare module.exports: any;
}

declare module 'fuse/test/javascript/src/twoDepends/depends-two' {
  declare module.exports: any;
}

declare module 'fuse/test/javascript/src/twoDepends/input' {
  declare module.exports: any;
}

declare module 'fuse/test/module/depends/app' {
  declare module.exports: any;
}

declare module 'fuse/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fuse/bin/fuse.js' {
  declare module.exports: $Exports<'fuse/bin/fuse'>;
}
declare module 'fuse/lib/fuse.js' {
  declare module.exports: $Exports<'fuse/lib/fuse'>;
}
declare module 'fuse/lib/index.js' {
  declare module.exports: $Exports<'fuse/lib/index'>;
}
declare module 'fuse/lib/mustache.js' {
  declare module.exports: $Exports<'fuse/lib/mustache'>;
}
declare module 'fuse/test/javascript/expected/depends/basic-depends-result.js' {
  declare module.exports: $Exports<'fuse/test/javascript/expected/depends/basic-depends-result'>;
}
declare module 'fuse/test/javascript/expected/import/basic-import-result.js' {
  declare module.exports: $Exports<'fuse/test/javascript/expected/import/basic-import-result'>;
}
declare module 'fuse/test/javascript/expected/include/basic-include-result.js' {
  declare module.exports: $Exports<'fuse/test/javascript/expected/include/basic-include-result'>;
}
declare module 'fuse/test/javascript/expected/twoDepends/result.js' {
  declare module.exports: $Exports<'fuse/test/javascript/expected/twoDepends/result'>;
}
declare module 'fuse/test/javascript/src/depends/basic-depends.js' {
  declare module.exports: $Exports<'fuse/test/javascript/src/depends/basic-depends'>;
}
declare module 'fuse/test/javascript/src/depends/depends-one.js' {
  declare module.exports: $Exports<'fuse/test/javascript/src/depends/depends-one'>;
}
declare module 'fuse/test/javascript/src/import/basic-import.js' {
  declare module.exports: $Exports<'fuse/test/javascript/src/import/basic-import'>;
}
declare module 'fuse/test/javascript/src/import/import-one.js' {
  declare module.exports: $Exports<'fuse/test/javascript/src/import/import-one'>;
}
declare module 'fuse/test/javascript/src/include/basic-include.js' {
  declare module.exports: $Exports<'fuse/test/javascript/src/include/basic-include'>;
}
declare module 'fuse/test/javascript/src/include/include-one.js' {
  declare module.exports: $Exports<'fuse/test/javascript/src/include/include-one'>;
}
declare module 'fuse/test/javascript/src/lint/lint.js' {
  declare module.exports: $Exports<'fuse/test/javascript/src/lint/lint'>;
}
declare module 'fuse/test/javascript/src/lint/lintfree.js' {
  declare module.exports: $Exports<'fuse/test/javascript/src/lint/lintfree'>;
}
declare module 'fuse/test/javascript/src/noDepends/input.js' {
  declare module.exports: $Exports<'fuse/test/javascript/src/noDepends/input'>;
}
declare module 'fuse/test/javascript/src/twoDepends/depends-one.js' {
  declare module.exports: $Exports<'fuse/test/javascript/src/twoDepends/depends-one'>;
}
declare module 'fuse/test/javascript/src/twoDepends/depends-two.js' {
  declare module.exports: $Exports<'fuse/test/javascript/src/twoDepends/depends-two'>;
}
declare module 'fuse/test/javascript/src/twoDepends/input.js' {
  declare module.exports: $Exports<'fuse/test/javascript/src/twoDepends/input'>;
}
declare module 'fuse/test/module/depends/app.js' {
  declare module.exports: $Exports<'fuse/test/module/depends/app'>;
}
declare module 'fuse/test/test.js' {
  declare module.exports: $Exports<'fuse/test/test'>;
}
